channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.3
  - pip==19.2.2
  - gunicorn==20.0.4
  - python-arango==6.0.0
  - dash==1.17.0
  - dash-bootstrap-components==0.10.7
  - requests==2.24.0
  - jsonschema==3.2.0
  - pandas==1.1.1
  - pytest==6.0.1
  - tenacity==6.2.0
  - tqdm==4.50.0
  - orjson==3.4.3
  - lxml==4.6.1
  - xlrd==1.2.0
  - numba==0.51.2
  - profilehooks==1.12.0
