channels:
  - defaults
dependencies:
  - python==3.7.5
  - jsonschema==3.2.0
  - pandas==1.1.1
  - requests==2.24.0
  - pip==19.2.2
  - pytest==6.0.1
  - aiohttp==3.6.2
  - gunicorn==20.0.4
  - openpyxl
  - pip:
      - lxml==4.4.2
      - dash==1.15.0
      - python-arango==5.4.0
