debug = false
logLevel = "INFO"

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    [entryPoints.https.tls]
  [entryPoints.admin]
    address = "127.0.0.1:1337"
    [entryPoints.admin.auth]
      [entryPoints.admin.auth.basic]
        users = ["admin:$apr1$TIvpJ2.c$bYGTekHTnDq9gExf/ycdl."]

[api]
  entryPoint = "admin"
  dashboard = true
  [api.statistics]
    recentErrors = 20

[acme]
  email = "knapiontek@gmail.com"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  onDemand = false
  [acme.httpChallenge]
    entryPoint = "http"
  [[acme.domains]]
    main = "gecko-code.info"
    sans = ["trend.gecko-code.info", "admin.gecko-code.info"]

[rest]
  entryPoint = "admin"

[file]

[backends]
  [backends.admin]
    [backends.admin.servers]
      [backends.admin.servers.main]
        url = "http://127.0.0.1:1337"

[frontends]
  [frontends.admin]
    entryPoints = ["http", "https"]
    backend = "admin"
    passHostHeader = true
    [frontends.admin.routes]
      [frontends.admin.routes.main]
        rule = "Host:admin.gecko-code.info"
